snapshots:
  - name: producthistory
    relation: ref('CDC_with_dbt', 'product')
    description:  Slow-changing dimension view of product
    config:
      database: cdcdemo
#      schema: dbt
      strategy: check
      unique_key: ProductKey
      check_cols: all
      hard_deletes: invalidate 