snapshots:
  - name: product-history
    relation: ref('product')
    description:  Slow-changing dimension view of product
    config:
      database: cdcdemo
      schema: dbt
      strategy: check
      unique_key: ProductKey
      check_cols: all
      hard_deletes: invalidate 